repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v4.0.1
   hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
    - id: check-ast
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-aws-credentials
    - id: end-of-file-fixer
    - id: detect-private-key
 - repo: https://github.com/psf/black
   rev: 21.6b0
   hooks:
    - id: black
 - repo: https://github.com/timothycrosley/isort
   rev: 5.9.1
   hooks:
    - id: isort
 - repo: https://gitlab.com/pycqa/flake8
   rev: 3.8.4
   hooks:
    - id: flake8
      additional_dependencies: [flake8-isort]
